In [1]:
import pandas as pd

In [2]:
xl = pd.ExcelFile("compras.xlsx")
xl.sheet_names

['vidrio', 'pintura', 'otros', 'aux_parametros', 'aux_listas']

In [3]:
xl.close()

In [4]:
xl = pd.ExcelFile("compras.xlsx")
xl.sheet_names

['vidrio', 'pintura', 'otros', 'aux_parametros', 'aux_listas']

In [5]:
xl.close()

In [6]:
xl = pd.ExcelFile("compras.xlsx")
xl.sheet_names

['vidrio', 'pintura', 'otros', 'aux_parametros', 'aux_listas']

In [7]:
xl = pd.ExcelFile("compras.xlsx")
df_main = pd.DataFrame()
for sheet in xl.sheet_names:
    print(sheet)
    if "aux" not in sheet:
        df = pd.read_excel(xl, sheet)
        df_main = pd.concat([df_main, df])
        
df_main.to_excel("compras_consolidado.xlsx")

vidrio
pintura
otros
aux_parametros
aux_listas

C:\Users\Marco\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
C:\Users\Marco\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
C:\Users\Marco\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [8]:
xl.close()

In [9]:
df_main

,articulo,unidad,costo_ars,costo_usd,costo_eur,tipo,condicion_pago_dias,peso_kg,diametro_mm,asa,consumo_g_cm2,consumo_estandar,velocidad_aplicacion_u_h
0,Botella de salsa de tomate x 1000cc Cattorini,$/u,65.42,NaN,NaN,VIDRIO,30.0,NaN,NaN,NaN,NaN,NaN,NaN
1,platpo playo ceramica blanco (Ancers),$/u,780.78,NaN,NaN,VIDRIO,20.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Botella de salsa de tomate x 500cc RIGOLLEAU (...,$/u,52.92,NaN,NaN,VIDRIO,60.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Botella STD 355 cc RIGOLLEAU ( AM 08902),$/u,36.47,NaN,NaN,VIDRIO,60.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Botella ultrliviana 500cc RIGOLLEAU (AM 08102),$/u,50.35,NaN,NaN,VIDRIO,60.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22,Caja ind,$/u,5.00,NaN,NaN,EMBALAJE_ESPECIAL,NaN,NaN,NaN,NaN,NaN,NaN,1000.0
23,"Caja Growler x 6 con division 167,18 por caja,...",$/u,46.33,NaN,NaN,EMBALAJE_ESPECIAL,NaN,NaN,NaN,NaN,NaN,NaN,800.0
24,"Caja Gin x 6 con divisor 98,15 por caja",$/u,16.35,NaN,NaN,EMBALAJE_ESPECIAL,NaN,NaN,NaN,NaN,NaN,NaN,800.0
25,Tapa growler plastica negra (MEGAENVASES),$/u,18.46,NaN,NaN,EMBALAJE_ESPECIAL,NaN,NaN,NaN,NaN,NaN,NaN,800.0
26,Caja x12,$/u,5.00,NaN,NaN,EMBALAJE_ESPECIAL,NaN,NaN,NaN,NaN,NaN,NaN,700.0

In [12]:
import datetime as dt
df_main["update_date"] = dt.date.today().strftime('%d/%m/%Y')
df_main

,articulo,unidad,costo_ars,costo_usd,costo_eur,tipo,condicion_pago_dias,peso_kg,diametro_mm,asa,consumo_g_cm2,consumo_estandar,velocidad_aplicacion_u_h,update_date
0,Botella de salsa de tomate x 1000cc Cattorini,$/u,65.42,NaN,NaN,VIDRIO,30.0,NaN,NaN,NaN,NaN,NaN,NaN,15/04/2023
1,platpo playo ceramica blanco (Ancers),$/u,780.78,NaN,NaN,VIDRIO,20.0,NaN,NaN,NaN,NaN,NaN,NaN,15/04/2023
2,Botella de salsa de tomate x 500cc RIGOLLEAU (...,$/u,52.92,NaN,NaN,VIDRIO,60.0,NaN,NaN,NaN,NaN,NaN,NaN,15/04/2023
3,Botella STD 355 cc RIGOLLEAU ( AM 08902),$/u,36.47,NaN,NaN,VIDRIO,60.0,NaN,NaN,NaN,NaN,NaN,NaN,15/04/2023
4,Botella ultrliviana 500cc RIGOLLEAU (AM 08102),$/u,50.35,NaN,NaN,VIDRIO,60.0,NaN,NaN,NaN,NaN,NaN,NaN,15/04/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22,Caja ind,$/u,5.00,NaN,NaN,EMBALAJE_ESPECIAL,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,15/04/2023
23,"Caja Growler x 6 con division 167,18 por caja,...",$/u,46.33,NaN,NaN,EMBALAJE_ESPECIAL,NaN,NaN,NaN,NaN,NaN,NaN,800.0,15/04/2023
24,"Caja Gin x 6 con divisor 98,15 por caja",$/u,16.35,NaN,NaN,EMBALAJE_ESPECIAL,NaN,NaN,NaN,NaN,NaN,NaN,800.0,15/04/2023
25,Tapa growler plastica negra (MEGAENVASES),$/u,18.46,NaN,NaN,EMBALAJE_ESPECIAL,NaN,NaN,NaN,NaN,NaN,NaN,800.0,15/04/2023
26,Caja x12,$/u,5.00,NaN,NaN,EMBALAJE_ESPECIAL,NaN,NaN,NaN,NaN,NaN,NaN,700.0,15/04/2023